# Cloudflare Pages 配置文件
name = "circlecropimage-app"

[build]
command = "npm run cf:build"
cwd = "."
watch_dir = ["src", "*.html", "*.js"]

[build.environment_variables]
NODE_VERSION = "18"
NPM_FLAGS = "--production=false"

# 静态资源缓存配置
[[headers]]
for = "/dist/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.html"
[headers.values]
"Cache-Control" = "public, max-age=3600"

[[headers]]
for = "*.css"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

# 安全头部
[[headers]]
for = "/*"
[headers.values]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"Referrer-Policy" = "strict-origin-when-cross-origin"
"Permissions-Policy" = "camera=(), microphone=(), geolocation=()"